[window]
blur = true
opacity = 0.90
option_as_alt = "Both"
dynamic_padding = true
decorations = "Buttonless"
padding = { x = 2, y = 0 }

[font]
size = 14.0
offset = { x = 0, y = 10 }
glyph_offset = { x = 0, y = 4 }
normal = { family = "Hack Nerd Font Mono", style = "Regular" }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true

[colors.cursor]
cursor = "#839496"

[colors.primary]
background = "#001A1B"
foreground = "#839496"

[colors.normal]
black = "#110f18"
blue = "#a277ff"
cyan = "#61ffca"
green = "#61ffca"
magenta = "#a277ff"
red = "#ff6767"
white = "#edecee"
yellow = "#ffca85"

[colors.bright]
black = "#4d4d4d"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "T"
mods = "Command"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "LBracket"
mods = "Alt"
