tap "homebrew/bundle"
tap "koekeishiya/formulae"
tap "oven-sh/bun"

brew "git"
brew "difftastic"
brew "git-delta"
brew "ripgrep"
brew "fd"
brew "eza"
brew "genact" # nonsense activity generator -- pretend to be busy
brew "gum"  # markdown renderer
brew "chafa"  # terminal image renderer
brew "imagemagick"  # image file processor
brew "sox"  # audio file processor
brew "ffmpeg"  # video file processor
brew "wrk"  # HTTP benchmarking tool
brew "exiftool"
brew "fish"
brew "fisher"
brew "jq"
brew "ast-grep"
brew "task" # todo list
brew "tokei"  # code line summary
brew "vhs"  # generate GIFs with terminal code
brew "bat"
brew "zoxide"
brew "fzf"
brew "tlrc"  # community effort man page
brew "tmux"
brew "btop"
brew "watch"
brew "yazi"
brew "lazygit"
brew "skhd"
brew "yabai"
brew "node"
brew "bun"
brew "pnpm"
brew "stylua"
brew "shfmt"
brew "golangci-lint"
brew "selene"
brew "shellcheck"
brew "lua"
brew "luarocks"
brew "luacheck"
brew "python3"
brew "python-setuptools"
brew "rustup-init"
brew "golang"
brew "ruby"
brew "neovim"

cask "font-hack-nerd-font"
cask "font-cascadia-mono"
cask "ghostty"
cask "alacritty"
cask "kitty"
cask "neovide"
cask "zed"
cask "scroll-reverser"
cask "karabiner-elements"
cask "raycast"
cask "alfred"
cask "cleanshot"
cask "bartender"
cask "alt-tab"
cask "keka"
cask "typora"
cask "arc"
cask "firefox@developer-edition"
cask "google-chrome"
cask "iina"
cask "figma"
cask "blender"
cask "adobe-creative-cloud"
cask "qq"
cask "qqmusic"
cask "wechat"
