disableStartupPopups: true
os:
  editPreset: 'nvim'
git:
  diffRenderers:
    - command: difft --color=always
      type: extDiff
gui:
  nerdFontsVersion: "3"
  showFileIcons: false
  filterMode: fuzzy
  mouseEvents: false
